file:
  upload-dir: ./uploads
server:
  port: 8089
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/file_upload?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
